### ISSUE TITLE
student_dashboard.html not working.

### ISSUE THREAD

**Issue by ChetanKhanna** [PS-Division-BITS/TMS#26]
The links on all buttons are broken. Also the note mentioning re-attempts is incorrect since we only have one re-application.

**Comment by ChetanKhanna** [comment]
I think the broken buttons are on website_base.html.

**Comment by ChetanKhanna** [comment]
Also, the header with 'having troubles' and a button before 'developers.psd@gmail.com' isn't working.

**Comment by Oytrik** [comment]
Done.
