### ISSUE TITLE
Modify PSD to add more functionality

### ISSUE THREAD

**Issue by ChetanKhanna** [PS-Division-BITS/TMS#49]
Currently the PSD user only changes the deadline that is to be displayed on the front-end.
Also give the PSD user ability to enable/disable any type of transfer at any point of time (so that the corresponding links from the student dashboard disappears) Also, segregate the deadlines of TS2PS and PS2TS, currently there's only one. The following files will be changed:
- PSD model in `models.py` to store different deadlines and active status of type of transfers
- A new html file for PSD user.
- A `psd_view` for passing on the status and deadline to the `student_dashboard`.
- `student_dashboard.html` for reflecting these changes accordingly.
- `student_views` for passing all these statuses and deadlines to the front-end.

What I propose is that instead of a new `deadlines` model, we add `deadline` and `is_active` fields to the `TS2PSTransfer` and `PS2TSTransfer` models. And write view/htmls accordingly.

**Comment by nrupeshsurya** [comment]
Storing the data in the PS2TSTransfer and TS2PSTransfer is storing redundant data? Is_active feature seems doable and relevant

**Comment by ChetanKhanna** [comment]
Actually you are correct.
If we give `deadline` or even `is_active` in the Transfer tables, each record will unnecessarily be having that data.
We should come up with something better. So maybe another table just for storing this information? Since it is needed only once per transfer table?

**Comment by nrupeshsurya** [comment]
is_active is a field which can be specified for each application so maybe integrate them locally so that PSD user can disable them. After that we can check the condition while passing through the stages. (Set enable by default).  Set it as false through the PSD view

**Comment by ChetanKhanna** [comment]
@nrupeshsurya @AdarshNandanwar rebase and make a fresh PR. If you face any issues regarding rebasing, let me know.
@KritiKukreja please send the PR to the correct repository this time :)
