### ISSUE TITLE
Form fontend/backend changes

### ISSUE THREAD

**Issue by ChetanKhanna** [PS-Division-BITS/TMS#79]
1. Display student name, ID and branch on top of each form
2. Fix HOD option for each applicant depending upon student's branch. For dual degree student, give them option to select between the two HOD's
3. Add phone number field in form
4. Change field name in form supervisor --> supervisor/co-supervisor
5. In locale drop down, add one more option -- 'off-campus industry'
Also, when this option is selected, display a warning:
"If you're opting for off campus industry, make sure the industry is not already listed as a PS station"
6. Change field name in form Name of organization --> Name of institute/organization

**Comment by ChetanKhanna** [comment]
@AdarshNandanwar

**Comment by ChetanKhanna** [comment]
for 1. take branch from Student ID.
for 3. I think there is a contact number field in user model, use that
for 5. Add the option in corresponding models

**Comment by AdarshNandanwar** [comment]
Where is student ID stored?
Also should the phone number in the form be readonly as it is linked with the user model?

**Comment by AdarshNandanwar** [comment]
Also, there is currently no way of getting department of the HOD.

**Comment by ChetanKhanna** [comment]
Student ID is stored in the `username` field.
No, we want the student to fill the phone number, we don't have it initially. So can't keep it read only.
To get the department of HOD use their email. HOD emails are of fixed format, for example, hod.economics@goa.bits-pilani.ac.in
